apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-gateway.fullname" . }}-config-update-token
  namespace: {{ include "mcp-gateway.namespace" . }}
  labels:
    {{- include "mcp-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ randAlphaNum 32 | b64enc | quote }}
