---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-gateway.brokerServiceAccountName" . }}
  namespace: {{ include "mcp-gateway.namespace" . }}
  labels:
    {{- include "mcp-gateway.labels" . | nindent 4 }}
    component: broker-router
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-gateway.controllerServiceAccountName" . }}
  namespace: {{ include "mcp-gateway.namespace" . }}
  labels:
    {{- include "mcp-gateway.labels" . | nindent 4 }}
    component: controller
