apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: mcp-auth-policy
  namespace: gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: mcp-gateway
    sectionName: mcp
  defaults:
    when:
      - predicate: "!request.path.contains('/.well-known')"
    rules:
      authentication:
        'keycloak':
          jwt:
            issuerUrl: http://keycloak.keycloak.svc.cluster.local/realms/mcp
      authorization:
        'allow-tool-list':
          patternMatching:
            patterns:
              - predicate: size(auth.identity.groups) >=0
              - predicate: request.headers['x-mcp-method'] in ["tools/list","initialize","notifications/initialized"] # add method header
      response:
        success:
          headers:
            # copy X-MCP-API-Key to authorization after OAuth validation (if present)
            # this allows OAuth and backend API keys to coexist (issue #201)
            'authorization':
              value: "{request.headers['x-mcp-api-key']}"
        unauthorized:
          code: 401
          headers:
            'WWW-Authenticate':
              value: Bearer resource_metadata=http://mcp.127-0-0-1.sslip.io:8888/.well-known/oauth-protected-resource/mcp
          body:
            value: |
              {
                "error": "Forbidden",
                "message": "Access denied."
              }
        unauthenticated:
          code: 401
          headers:
            'WWW-Authenticate':
              value: Bearer resource_metadata=http://mcp.127-0-0-1.sslip.io:8888/.well-known/oauth-protected-resource/mcp
          body:
            value: |
              {
                "error": "Forbidden",
                "message": "Access denied."
              }
