---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-broker-router
  namespace: mcp-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-controller
  namespace: mcp-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-controller
rules:
  - apiGroups: ["mcp.kagenti.com"]
    resources: ["mcpgateways"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["mcp.kagenti.com"]
    resources: ["mcpgateways/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-controller
subjects:
  - kind: ServiceAccount
    name: mcp-controller
    namespace: mcp-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mcp-broker-router
  namespace: mcp-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["mcp-gateway-config"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mcp-broker-router
  namespace: mcp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mcp-broker-router
subjects:
  - kind: ServiceAccount
    name: mcp-broker-router
    namespace: mcp-system
